apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: annotating-webhook
webhooks:
  - name: annotating-webhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        annotating-webhook-enabled: "true"
    clientConfig:
      service:
        name: annotating-webhook
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVZXBPTWFUSHVUazljcFVpNkE4Uk93VmZCeGxRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qRXdPREUwCk1URTBOREF3V2hjTk1qWXdPREV6TVRFME5EQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMa0IxVzdNCkZodG5rQkV2ZWxYOXZpVVFLWjNiOHJXTVdJd0I3VDkwRFIvSlY5d3NCcVFkTEcvRW9KdS9XaXp0cDFicGg5U1UKWERaOGJhdlo2WW1PV1Y4dHNLZHpqTUQvN3ZqREtZNm9nTmUxc3AzZ3EzMGlSblFFeHBPeFVhQ3dyYXh5Wkh6SQo5azJPdVNsUEtzMENYOFhPa2YrQzZUSC9lVllIRHpoNXhFVzR3VDQ0cnNQWHcrcVUwUjJEeG5HOGczVkExbUoxCktxUzZLSlYrUFRuU2tyQUdSUHFXRHZxWW1xbkhMZDAxVlV0SGhGVVJiRkk1Y2phVXJFSk5CcmtGNGdPbTlqSVAKM2NyV0VMUTdtRlRIWXhvR2RFMFpKZmFvanN5QzdIUU9QbzRKWko2SEdFaGExdlFPMEk0ZjVVeFNHdEJjTjZMYwpmdXhleGo1eWhPUnlkUThDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRktkNnFiNnlGUS9HeEVaZU5IZ2llNDRJRXNBT01BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUNoazRGVVA3TmNzaUlEcm4xSDVTR214bm8rWDVsUFRqb3poenVzSzJHVGVHTFdNS0lTa3hqRQp4cWpxeGFUeXcrc3FLVEtzQ3dQSU44TXBlZGJIeW9WWTVKMGZzU0xzaFZZRkpqcUkwVkZRWForR1dXSzN4dFMxCllaU01kSTNCT0o1YnF3WTI0SDNta3ZIa29lVVhBdmdwOHEwdG8vaEhRWkM4KzNNVUkzT1ZtQlR2ZEpsejNDQUwKR212SmZ1R0JIaU5SUGNhZXJneGdid1p1TVZLR2NJb0lmWDJWcnpqbEVWUFo2bU5kaTE3VHgyWDZQQzVBYTErYgpMOVJrRkpKenBFdHJVTGN5Uy91Z3d2MXp4eXFiV1JIVXlCdFIwS20rTXhjQVBieURoSStOaXlodWxTQUtVU3pVCmNzT04ybE5BUUszdXZDRnREQ282YUcrRlNKTHFrQXpjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["apps"]
        apiVersions: ["v1", "v1beta1"]
        resources: ["pods", "replicasets"]